# Generated by Django 5.1.2 on 2025-10-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la marca', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol', max_length=60)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del rol', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_inicial', models.IntegerField(help_text='Precio inicial de la subasta')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la subasta')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la subasta')),
                ('estado', models.CharField(default='activa', help_text='Estado de la subasta', max_length=20)),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'db_table': 'subastas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modelo', max_length=45)),
                ('marca', models.ForeignKey(help_text='Marca del modelo', on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='venta.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelos',
                'ordering': ['nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=60)),
                ('apellido', models.CharField(help_text='Apellido del usuario', max_length=60)),
                ('correo', models.EmailField(help_text='Correo electrónico del usuario', max_length=80, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha de creación del usuario')),
                ('estado', models.CharField(default='activo', help_text='Estado del usuario', max_length=20)),
                ('rol', models.ForeignKey(help_text='Rol del usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='venta.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(help_text='Monto de la puja')),
                ('fecha_puja', models.DateField(auto_now_add=True, help_text='Fecha de la puja')),
                ('subasta', models.ForeignKey(help_text='Subasta de la puja', on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='venta.subasta')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la puja', on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='venta.usuario')),
            ],
            options={
                'verbose_name': 'Puja',
                'verbose_name_plural': 'Pujas',
                'db_table': 'pujas',
                'ordering': ['-fecha_puja'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Acción realizada', max_length=60)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha de la acción')),
                ('ip', models.CharField(blank=True, help_text='Dirección IP', max_length=25, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='venta.usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'logs_actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(help_text='Año del vehículo')),
                ('precio', models.IntegerField(help_text='Precio del vehículo')),
                ('tipo_transmision', models.CharField(help_text='Tipo de transmisión', max_length=60)),
                ('tipo_combustible', models.CharField(help_text='Tipo de combustible', max_length=60)),
                ('kilometraje', models.IntegerField(help_text='Kilometraje del vehículo')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del vehículo', max_length=150, null=True)),
                ('estado', models.CharField(default='disponible', help_text='Estado del vehículo', max_length=20)),
                ('fecha_publicacion', models.DateField(auto_now_add=True, help_text='Fecha de publicación')),
                ('marca', models.ForeignKey(help_text='Marca del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='venta.marca')),
                ('modelo', models.ForeignKey(help_text='Modelo del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='venta.modelo')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='venta.usuario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='subasta',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo en subasta', on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='venta.vehiculo'),
        ),
        migrations.CreateModel(
            name='SolicitudVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', help_text='Estado de la solicitud', max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True, help_text='Fecha de solicitud')),
                ('fecha_respuesta', models.DateField(blank=True, help_text='Fecha de respuesta', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que solicita la verificación', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_verificacion', to='venta.usuario')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo a verificar', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_verificacion', to='venta.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de Verificación',
                'verbose_name_plural': 'Solicitudes de Verificación',
                'db_table': 'solicitudes_verificacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(help_text='Tipo de documento', max_length=50)),
                ('archivo_url', models.CharField(help_text='URL del archivo', max_length=150)),
                ('fecha_subida', models.DateField(auto_now_add=True, help_text='Fecha de subida')),
                ('estado', models.CharField(default='pendiente', help_text='Estado del documento', max_length=20)),
                ('comentario_admin', models.CharField(blank=True, help_text='Comentario del administrador', max_length=200, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario dueño del documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='venta.usuario')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo asociado al documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='venta.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='VehiculoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.CharField(help_text='URL de la imagen', max_length=150)),
                ('vehiculo', models.ForeignKey(help_text='Vehículo de la foto', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='venta.vehiculo')),
            ],
            options={
                'verbose_name': 'Foto de Vehículo',
                'verbose_name_plural': 'Fotos de Vehículos',
                'db_table': 'vehiculo_fotos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(help_text='Fecha de la venta')),
                ('precio_final', models.IntegerField(help_text='Precio final de la venta')),
                ('metodo_pago', models.CharField(help_text='Método de pago', max_length=20)),
                ('estado', models.CharField(default='pendiente', help_text='Estado de la venta', max_length=20)),
                ('comprador', models.ForeignKey(help_text='Comprador del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='venta.usuario')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo vendido', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='venta.vehiculo')),
                ('vendedor', models.ForeignKey(help_text='Vendedor del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='venta.usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
