# Generated by Django 5.1.2 on 2025-10-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default=1, help_text='Contraseña del usuario', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(default=1, help_text='Token de sesion del usuario', max_length=256),
            preserve_default=False,
        ),
    ]
