# Generated by Django 5.1.2 on 2025-11-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_usuario_contrasena_usuario_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del perfil del usuario', max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección del usuario', max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde reside el usuario', max_length=100, null=True)),
                ('foto_perfil', models.URLField(blank=True, help_text='URL de la foto de perfil', max_length=500, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del perfil')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfiles',
                'ordering': ['usuario'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre concatenado del usuario', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(default='Automovil', help_text='Tipo de vehículo (auto, moto, etc.)', max_length=60),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.CharField(blank=True, db_index=True, help_text='Ubicación del vehículo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(help_text='Apellido del usuario', max_length=150),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['ubicacion'], name='vehiculos_ubicaci_1ade54_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['precio'], name='vehiculos_precio_a25a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['año'], name='vehiculos_año_c0f846_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['marca', 'modelo'], name='vehiculos_marca_i_405b56_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='vehiculos_estado_bf04b7_idx'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(help_text='Usuario asociado al perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='venta.usuario'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['usuario'], name='perfiles_usuario_e55d7c_idx'),
        ),
    ]
