# Generated by Django 5.1.2 on 2025-10-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0002_usuario_contrasena_usuario_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="contrasena",
            field=models.CharField(
                help_text="Contraseña del usuario", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="token",
            field=models.CharField(
                help_text="Token de sesion del usuario", max_length=128, unique=True
            ),
        ),
    ]
