# Generated by Django 5.1.2 on 2025-11-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_usuario_contrasena_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(default='Automovil', help_text='Tipo de vehículo (auto, moto, etc.)', max_length=60),
        ),
    ]
