# Generated by Django 5.1.2 on 2025-11-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_perfil_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='vehiculofoto',
            name='url_imagen',
            field=models.ImageField(blank=True, help_text='Imagen del vehículo', null=True, upload_to='vehiculos/'),
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la conversación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la conversación')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la conversación está activa')),
                ('comprador', models.ForeignKey(help_text='Comprador de la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_comprador', to='venta.usuario')),
                ('vendedor', models.ForeignKey(help_text='Vendedor de la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_vendedor', to='venta.usuario')),
                ('venta', models.OneToOneField(blank=True, help_text='Venta asociada a esta conversación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='venta.venta')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'conversaciones',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de envío del mensaje')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó el mensaje', null=True)),
                ('conversacion', models.ForeignKey(help_text='Conversación a la que pertenece el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='venta.conversacion')),
                ('remitente', models.ForeignKey(help_text='Usuario que envió el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='venta.usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
