# Generated by Django 5.1.2 on 2025-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0004_alter_usuario_contrasena_alter_usuario_correo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="correo",
            field=models.EmailField(
                help_text="Correo electrónico del usuario", max_length=80, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="token",
            field=models.CharField(
                help_text="Token de sesion del usuario", max_length=256, unique=True
            ),
        ),
    ]
