# Generated by Django 5.1.2 on 2025-11-15 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_cambiar_mensaje_a_venta'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mensaje',
            name='mensajes_venta_i_c01638_idx',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='comprador',
            field=models.ForeignKey(blank=True, help_text='Usuario comprador en la conversación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_como_comprador', to='venta.usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='Vehículo sobre el que se está conversando', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='venta.vehiculo'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Usuario vendedor en la conversación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_como_vendedor', to='venta.usuario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(help_text='Usuario que envió el mensaje (puede ser comprador o vendedor)', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='venta.usuario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Venta asociada (opcional, para compatibilidad con datos antiguos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='venta.venta'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['comprador', 'vendedor', 'vehiculo'], name='mensajes_comprad_1452ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['fecha_envio'], name='mensajes_fecha_e_9e6258_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente'], name='mensajes_remiten_23cab3_idx'),
        ),
    ]
