# Generated by Django 5.1.2 on 2025-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0005_alter_usuario_correo_alter_usuario_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="token",
            field=models.CharField(
                help_text="Token de sesion del usuario", max_length=256
            ),
        ),
    ]
