# Generated by Django 5.1.2 on 2025-10-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0006_alter_usuario_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="tipo_vehiculo",
            field=models.CharField(
                default="Automovil",
                help_text="Tipo de vehículo (auto, moto, etc.)",
                max_length=60,
            ),
        ),
    ]
