# Generated by Django 5.1.2 on 2025-11-16 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_remove_mensaje_mensajes_venta_i_c01638_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del tipo de vehículo (Automóvil, Motocicleta, etc.)', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'db_table': 'tipos_vehiculo',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(help_text='Tipo de vehículo (auto, moto, etc.)', max_length=60),
        ),
        migrations.AddField(
            model_name='modelo',
            name='tipo_vehiculo',
            field=models.ForeignKey(default=1, help_text='Tipo de vehículo del modelo', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='venta.tipodevehiculo'),
            preserve_default=False,
        ),
    ]
