# Generated by Django 5.1.2 on 2025-11-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0006_cambiar_mensaje_a_comprador_vendedor_vehiculo"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mensaje",
            new_name="mensajes_comprad_1452ad_idx",
            old_name="mensajes_comprador_vendedor_vehiculo_idx",
        ),
        migrations.RenameIndex(
            model_name="mensaje",
            new_name="mensajes_fecha_e_9e6258_idx",
            old_name="mensajes_fecha_envio_idx",
        ),
        migrations.RenameIndex(
            model_name="mensaje",
            new_name="mensajes_remiten_23cab3_idx",
            old_name="mensajes_remitente_idx",
        ),
        migrations.AlterField(
            model_name="mensaje",
            name="remitente",
            field=models.ForeignKey(
                help_text="Usuario que envió el mensaje (puede ser comprador o vendedor)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensajes_enviados",
                to="venta.usuario",
            ),
        ),
    ]
