# Generated by Django 5.1.2 on 2025-11-23 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venta", "0007_tipodevehiculo_alter_vehiculo_tipo_vehiculo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Calificación de 0 a 5 (ej: 1.5, 4.5)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True,
                        help_text="Comentario sobre la venta",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creación de la valoración",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "comprador",
                    models.ForeignKey(
                        help_text="Comprador que realiza la valoración",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valoraciones_realizadas",
                        to="venta.usuario",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        help_text="Venta que se está valorando",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="venta.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valoración",
                "verbose_name_plural": "Valoraciones",
                "db_table": "valoraciones",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("venta", "comprador")},
            },
        ),
    ]
