# Generated by Django 5.1.2 on 2025-11-25 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='administrador_que_evaluo',
            field=models.ForeignKey(blank=True, help_text='Administrador que evaluó el vehículo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiculos_evaluados', to='venta.usuario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nota_de_administrador',
            field=models.CharField(blank=True, help_text='Nota de administrador', max_length=250, null=True),
        ),
    ]
